# Healthcare_Project.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject_healthcare
  labels:
    app: myproject_healthcare-lbl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: HealthCare
    spec:
      containers:
      - name: financeme
        image: chrisdee10/healthcare:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
  selector:
    matchLabels:
      app: HealthCare

---
apiVersion: v1
kind: Service
metadata:
  name: myproject_HealthCare-service
  labels:
    app: myproject_HealthCare-lbl
spec:
  type: NodePort
  selector:
    app: HealthCare
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31039